### ISSUE TITLE
Logo for PyTorn

### ISSUE THREAD

**Issue by shubhodeep9** [pytorn/artwork#1]
Need for a logo for this application, that will be the logo for the organization too.
Cont. to https://github.com/pytorn/torn/issues/9

**Comment by shubhodeep9** [comment]
@andeladenaro Hi, please create a PR to this repo.

**Comment by andeladenaro** [comment]
You can download the files [here](https://drive.google.com/open?id=14i0uReLC8mquBhpLE6cFY4op7d9Kg7L2).
